// Location data for programmatic SEO - 70km Radius von Feucht (90537)
export interface LocationData {
  name: string
  slug: string
  title: string
  description: string
  distance: string
  population: string
  postalCodes: string[]
  neighborhoods?: string[]
  landmarks?: string[]
  lat: number
  lng: number
  priority?: 'high' | 'medium' | 'low' // Für Website-Anzeige
}

export const locations: LocationData[] = [
  // ========== PRIORITÄT HOCH - Werden auf Website angezeigt (0-25km) ==========
  
  // Basis & Hauptstädte
  {
    name: 'Feucht',
    slug: 'feucht',
    title: 'Entrümpelung Feucht',
    description: 'Ihr lokaler Partner in Feucht. Direkt vor Ort im Nürnberger Land.',
    distance: '0 km',
    population: '14.000',
    postalCodes: ['90537'],
    neighborhoods: ['Moosbach', 'Gauchsbach'],
    landmarks: ['Zeidelmuseum', 'Ortskern Feucht'],
    lat: 49.3758,
    lng: 11.2103,
    priority: 'high',
  },
  {
    name: 'Nürnberg',
    slug: 'nuernberg',
    title: 'Entrümpelung Nürnberg',
    description: 'Professionelle Entrümpelung in Nürnberg und allen Stadtteilen.',
    distance: '12 km',
    population: '518.000',
    postalCodes: ['90402', '90403', '90408', '90409', '90411', '90419', '90429', '90431', '90439', '90441', '90443', '90449', '90451', '90453', '90455', '90459', '90461', '90469', '90471', '90473', '90475', '90478', '90480', '90482'],
    neighborhoods: ['Altstadt', 'Gostenhof', 'St. Johannis', 'Maxfeld', 'Mögeldorf', 'Langwasser'],
    landmarks: ['Nürnberger Burg', 'Hauptmarkt', 'Lorenzkirche'],
    lat: 49.4521,
    lng: 11.0767,
    priority: 'high',
  },
  {
    name: 'Fürth',
    slug: 'fuerth',
    title: 'Entrümpelung Fürth',
    description: 'Zuverlässige Entrümpelung in Fürth. Faire Preise und professioneller Service.',
    distance: '18 km',
    population: '128.000',
    postalCodes: ['90762', '90763', '90765', '90766', '90768'],
    neighborhoods: ['Innenstadt', 'Hardhöhe', 'Dambach'],
    landmarks: ['Stadtpark', 'Fürther Freiheit'],
    lat: 49.4778,
    lng: 10.9881,
    priority: 'high',
  },
  {
    name: 'Schwabach',
    slug: 'schwabach',
    title: 'Entrümpelung Schwabach',
    description: 'Professionelle Entrümpelung in Schwabach.',
    distance: '19 km',
    population: '41.000',
    postalCodes: ['91126'],
    landmarks: ['Schwabacher Altstadt'],
    lat: 49.3297,
    lng: 11.0225,
    priority: 'high',
  },
  {
    name: 'Wendelstein',
    slug: 'wendelstein',
    title: 'Entrümpelung Wendelstein',
    description: 'Zuverlässige Entrümpelung in Wendelstein.',
    distance: '8 km',
    population: '16.000',
    postalCodes: ['90530'],
    lat: 49.3530,
    lng: 11.1500,
    priority: 'high',
  },
  {
    name: 'Altdorf',
    slug: 'altdorf',
    title: 'Entrümpelung Altdorf',
    description: 'Professionelle Entrümpelung in Altdorf bei Nürnberg.',
    distance: '15 km',
    population: '16.000',
    postalCodes: ['90518'],
    lat: 49.3869,
    lng: 11.3569,
    priority: 'high',
  },
  {
    name: 'Lauf an der Pegnitz',
    slug: 'lauf',
    title: 'Entrümpelung Lauf',
    description: 'Entrümpelung in Lauf an der Pegnitz.',
    distance: '18 km',
    population: '27.000',
    postalCodes: ['91207'],
    landmarks: ['Laufer Altstadt'],
    lat: 49.5119,
    lng: 11.2803,
    priority: 'high',
  },
  {
    name: 'Röthenbach an der Pegnitz',
    slug: 'roethenbach',
    title: 'Entrümpelung Röthenbach',
    description: 'Schnelle Entrümpelung in Röthenbach.',
    distance: '10 km',
    population: '12.000',
    postalCodes: ['90552'],
    lat: 49.4869,
    lng: 11.2436,
    priority: 'high',
  },
  {
    name: 'Schwaig',
    slug: 'schwaig',
    title: 'Entrümpelung Schwaig',
    description: 'Professionelle Entrümpelung in Schwaig.',
    distance: '15 km',
    population: '8.500',
    postalCodes: ['90571'],
    lat: 49.4750,
    lng: 11.1919,
    priority: 'high',
  },
  {
    name: 'Hersbruck',
    slug: 'hersbruck',
    title: 'Entrümpelung Hersbruck',
    description: 'Haushaltsauflösung in Hersbruck.',
    distance: '28 km',
    population: '12.500',
    postalCodes: ['91217'],
    lat: 49.5097,
    lng: 11.4308,
    priority: 'high',
  },
  {
    name: 'Schnaittach',
    slug: 'schnaittach',
    title: 'Entrümpelung Schnaittach',
    description: 'Entrümpelung in Schnaittach.',
    distance: '20 km',
    population: '8.500',
    postalCodes: ['91220'],
    lat: 49.5619,
    lng: 11.3358,
    priority: 'high',
  },
  {
    name: 'Allersberg',
    slug: 'allersberg',
    title: 'Entrümpelung Allersberg',
    description: 'Professionelle Entrümpelung in Allersberg.',
    distance: '18 km',
    population: '8.500',
    postalCodes: ['90584'],
    lat: 49.2589,
    lng: 11.2322,
    priority: 'high',
  },

  // ========== PRIORITÄT MITTEL - Weitere wichtige Städte (25-50km) ==========
  
  {
    name: 'Erlangen',
    slug: 'erlangen',
    title: 'Entrümpelung Erlangen',
    description: 'Professionelle Haushaltsauflösung in Erlangen.',
    distance: '28 km',
    population: '113.000',
    postalCodes: ['91052', '91054', '91056', '91058'],
    landmarks: ['Schloss Erlangen'],
    lat: 49.5897,
    lng: 11.0089,
    priority: 'medium',
  },
  {
    name: 'Roth',
    slug: 'roth',
    title: 'Entrümpelung Roth',
    description: 'Zuverlässige Entrümpelung in Roth.',
    distance: '25 km',
    population: '26.000',
    postalCodes: ['91154'],
    landmarks: ['Rothsee'],
    lat: 49.2444,
    lng: 11.0917,
    priority: 'medium',
  },
  {
    name: 'Neumarkt in der Oberpfalz',
    slug: 'neumarkt',
    title: 'Entrümpelung Neumarkt',
    description: 'Entrümpelung in Neumarkt.',
    distance: '42 km',
    population: '40.000',
    postalCodes: ['92318'],
    lat: 49.2806,
    lng: 11.4631,
    priority: 'medium',
  },
  {
    name: 'Forchheim',
    slug: 'forchheim',
    title: 'Entrümpelung Forchheim',
    description: 'Entrümpelung in Forchheim.',
    distance: '42 km',
    population: '32.000',
    postalCodes: ['91301'],
    lat: 49.7186,
    lng: 11.0581,
    priority: 'medium',
  },
  {
    name: 'Herzogenaurach',
    slug: 'herzogenaurach',
    title: 'Entrümpelung Herzogenaurach',
    description: 'Professionelle Entrümpelung in Herzogenaurach.',
    distance: '35 km',
    population: '24.000',
    postalCodes: ['91074'],
    lat: 49.5667,
    lng: 10.8833,
    priority: 'medium',
  },
  {
    name: 'Hilpoltstein',
    slug: 'hilpoltstein',
    title: 'Entrümpelung Hilpoltstein',
    description: 'Entrümpelung in Hilpoltstein.',
    distance: '22 km',
    population: '13.500',
    postalCodes: ['91161'],
    lat: 49.1917,
    lng: 11.1919,
    priority: 'medium',
  },
  {
    name: 'Neunkirchen am Brand',
    slug: 'neunkirchen',
    title: 'Entrümpelung Neunkirchen',
    description: 'Zuverlässige Entrümpelung in Neunkirchen.',
    distance: '30 km',
    population: '8.000',
    postalCodes: ['91077'],
    lat: 49.5917,
    lng: 11.1200,
    priority: 'medium',
  },
  {
    name: 'Ansbach',
    slug: 'ansbach',
    title: 'Entrümpelung Ansbach',
    description: 'Zuverlässige Entrümpelung in Ansbach.',
    distance: '62 km',
    population: '42.000',
    postalCodes: ['91522'],
    lat: 49.3006,
    lng: 10.5714,
    priority: 'medium',
  },
  {
    name: 'Weißenburg',
    slug: 'weissenburg',
    title: 'Entrümpelung Weißenburg',
    description: 'Entrümpelung in Weißenburg.',
    distance: '55 km',
    population: '18.000',
    postalCodes: ['91781'],
    lat: 49.0306,
    lng: 10.9711,
    priority: 'medium',
  },
  {
    name: 'Gunzenhausen',
    slug: 'gunzenhausen',
    title: 'Entrümpelung Gunzenhausen',
    description: 'Professionelle Entrümpelung in Gunzenhausen.',
    distance: '65 km',
    population: '16.500',
    postalCodes: ['91710'],
    lat: 49.1133,
    lng: 10.7561,
    priority: 'medium',
  },

  // ========== NIEDRIGE PRIORITÄT - Kleinere Orte & Gemeinden (Nur Landing Pages) ==========
  
  // Nürnberger Land - Klein
  {
    name: 'Rückersdorf',
    slug: 'rueckersdorf',
    title: 'Entrümpelung Rückersdorf',
    description: 'Professionelle Entrümpelung in Rückersdorf.',
    distance: '13 km',
    population: '3.800',
    postalCodes: ['90607'],
    lat: 49.4978,
    lng: 11.2419,
    priority: 'low',
  },
  {
    name: 'Happurg',
    slug: 'happurg',
    title: 'Entrümpelung Happurg',
    description: 'Entrümpelung in Happurg.',
    distance: '32 km',
    population: '3.500',
    postalCodes: ['91230'],
    lat: 49.4878,
    lng: 11.4989,
    priority: 'low',
  },
  {
    name: 'Velden',
    slug: 'velden',
    title: 'Entrümpelung Velden',
    description: 'Professionelle Entrümpelung in Velden.',
    distance: '35 km',
    population: '3.500',
    postalCodes: ['91235'],
    lat: 49.5597,
    lng: 11.5344,
    priority: 'low',
  },
  {
    name: 'Engelthal',
    slug: 'engelthal',
    title: 'Entrümpelung Engelthal',
    description: 'Zuverlässige Entrümpelung in Engelthal.',
    distance: '28 km',
    population: '2.800',
    postalCodes: ['91238'],
    lat: 49.4925,
    lng: 11.3900,
    priority: 'low',
  },
  {
    name: 'Pommelsbrunn',
    slug: 'pommelsbrunn',
    title: 'Entrümpelung Pommelsbrunn',
    description: 'Entrümpelung in Pommelsbrunn.',
    distance: '25 km',
    population: '2.700',
    postalCodes: ['91224'],
    lat: 49.5197,
    lng: 11.4431,
    priority: 'low',
  },
  {
    name: 'Röttenbach',
    slug: 'roettenbach',
    title: 'Entrümpelung Röttenbach',
    description: 'Entrümpelung in Röttenbach.',
    distance: '24 km',
    population: '4.200',
    postalCodes: ['91187'],
    lat: 49.2911,
    lng: 11.1683,
    priority: 'low',
  },
  {
    name: 'Schwarzenbruck',
    slug: 'schwarzenbruck',
    title: 'Entrümpelung Schwarzenbruck',
    description: 'Entrümpelung in Schwarzenbruck.',
    distance: '8 km',
    population: '8.500',
    postalCodes: ['90592'],
    lat: 49.3500,
    lng: 11.2333,
    priority: 'high',
  },
  {
    name: 'Ottensoos',
    slug: 'ottensoos',
    title: 'Entrümpelung Ottensoos',
    description: 'Entrümpelung in Ottensoos.',
    distance: '17 km',
    population: '1.500',
    postalCodes: ['91242'],
    lat: 49.5117,
    lng: 11.3547,
    priority: 'low',
  },
  {
    name: 'Neuhaus an der Pegnitz',
    slug: 'neuhaus-pegnitz',
    title: 'Entrümpelung Neuhaus',
    description: 'Entrümpelung in Neuhaus an der Pegnitz.',
    distance: '35 km',
    population: '2.900',
    postalCodes: ['91284'],
    lat: 49.6039,
    lng: 11.4864,
    priority: 'low',
  },
  {
    name: 'Reichenschwand',
    slug: 'reichenschwand',
    title: 'Entrümpelung Reichenschwand',
    description: 'Entrümpelung in Reichenschwand.',
    distance: '22 km',
    population: '1.700',
    postalCodes: ['91244'],
    lat: 49.5319,
    lng: 11.3792,
    priority: 'low',
  },

  // Erlangen-Höchstadt
  {
    name: 'Eckental',
    slug: 'eckental',
    title: 'Entrümpelung Eckental',
    description: 'Entrümpelung in Eckental.',
    distance: '22 km',
    population: '14.000',
    postalCodes: ['90542'],
    lat: 49.5758,
    lng: 11.1833,
    priority: 'high',
  },
  {
    name: 'Kalchreuth',
    slug: 'kalchreuth',
    title: 'Entrümpelung Kalchreuth',
    description: 'Entrümpelung in Kalchreuth.',
    distance: '18 km',
    population: '6.500',
    postalCodes: ['90562'],
    lat: 49.5483,
    lng: 11.1778,
    priority: 'low',
  },
  {
    name: 'Heroldsberg',
    slug: 'heroldsberg',
    title: 'Entrümpelung Heroldsberg',
    description: 'Entrümpelung in Heroldsberg.',
    distance: '17 km',
    population: '7.600',
    postalCodes: ['90562'],
    lat: 49.5408,
    lng: 11.1467,
    priority: 'low',
  },
  {
    name: 'Buckenhof',
    slug: 'buckenhof',
    title: 'Entrümpelung Buckenhof',
    description: 'Entrümpelung in Buckenhof.',
    distance: '22 km',
    population: '3.500',
    postalCodes: ['91054'],
    lat: 49.5847,
    lng: 11.0494,
    priority: 'low',
  },
  {
    name: 'Uttenreuth',
    slug: 'uttenreuth',
    title: 'Entrümpelung Uttenreuth',
    description: 'Entrümpelung in Uttenreuth.',
    distance: '24 km',
    population: '4.700',
    postalCodes: ['91080'],
    lat: 49.6036,
    lng: 11.0633,
    priority: 'low',
  },
  {
    name: 'Spardorf',
    slug: 'spardorf',
    title: 'Entrümpelung Spardorf',
    description: 'Entrümpelung in Spardorf.',
    distance: '25 km',
    population: '1.500',
    postalCodes: ['91080'],
    lat: 49.6133,
    lng: 11.0533,
    priority: 'low',
  },
  {
    name: 'Marloffstein',
    slug: 'marloffstein',
    title: 'Entrümpelung Marloffstein',
    description: 'Entrümpelung in Marloffstein.',
    distance: '26 km',
    population: '1.300',
    postalCodes: ['91080'],
    lat: 49.6217,
    lng: 11.0594,
    priority: 'low',
  },
  {
    name: 'Möhrendorf',
    slug: 'moehrendorf',
    title: 'Entrümpelung Möhrendorf',
    description: 'Entrümpelung in Möhrendorf.',
    distance: '28 km',
    population: '2.700',
    postalCodes: ['91096'],
    lat: 49.6319,
    lng: 10.9792,
    priority: 'low',
  },
  {
    name: 'Bubenreuth',
    slug: 'bubenreuth',
    title: 'Entrümpelung Bubenreuth',
    description: 'Entrümpelung in Bubenreuth.',
    distance: '27 km',
    population: '4.400',
    postalCodes: ['91088'],
    lat: 49.6344,
    lng: 11.0283,
    priority: 'low',
  },
  {
    name: 'Baiersdorf',
    slug: 'baiersdorf',
    title: 'Entrümpelung Baiersdorf',
    description: 'Entrümpelung in Baiersdorf.',
    distance: '32 km',
    population: '7.700',
    postalCodes: ['91083'],
    lat: 49.6589,
    lng: 11.0342,
    priority: 'low',
  },
  {
    name: 'Hemhofen',
    slug: 'hemhofen',
    title: 'Entrümpelung Hemhofen',
    description: 'Entrümpelung in Hemhofen.',
    distance: '32 km',
    population: '4.900',
    postalCodes: ['91334'],
    lat: 49.6611,
    lng: 10.9956,
    priority: 'low',
  },
  {
    name: 'Höchstadt an der Aisch',
    slug: 'hoechstadt',
    title: 'Entrümpelung Höchstadt',
    description: 'Entrümpelung in Höchstadt.',
    distance: '45 km',
    population: '13.000',
    postalCodes: ['91315'],
    lat: 49.7028,
    lng: 10.8131,
    priority: 'low',
  },

  // Landkreis Roth
  {
    name: 'Rednitzhembach',
    slug: 'rednitzhembach',
    title: 'Entrümpelung Rednitzhembach',
    description: 'Entrümpelung in Rednitzhembach.',
    distance: '14 km',
    population: '7.200',
    postalCodes: ['91126'],
    lat: 49.3294,
    lng: 11.0747,
    priority: 'low',
  },
  {
    name: 'Abenberg',
    slug: 'abenberg',
    title: 'Entrümpelung Abenberg',
    description: 'Entrümpelung in Abenberg.',
    distance: '28 km',
    population: '5.700',
    postalCodes: ['91183'],
    lat: 49.2444,
    lng: 10.9583,
    priority: 'low',
  },
  {
    name: 'Greding',
    slug: 'greding',
    title: 'Entrümpelung Greding',
    description: 'Entrümpelung in Greding.',
    distance: '38 km',
    population: '7.000',
    postalCodes: ['91171'],
    lat: 49.0447,
    lng: 11.3544,
    priority: 'low',
  },
  {
    name: 'Thalmässing',
    slug: 'thalmaessing',
    title: 'Entrümpelung Thalmässing',
    description: 'Entrümpelung in Thalmässing.',
    distance: '32 km',
    population: '5.700',
    postalCodes: ['91177'],
    lat: 49.1317,
    lng: 11.2278,
    priority: 'low',
  },
  {
    name: 'Spalt',
    slug: 'spalt',
    title: 'Entrümpelung Spalt',
    description: 'Entrümpelung in Spalt.',
    distance: '35 km',
    population: '5.200',
    postalCodes: ['91174'],
    lat: 49.1778,
    lng: 10.9250,
    priority: 'low',
  },
  {
    name: 'Georgensgmünd',
    slug: 'georgensmund',
    title: 'Entrümpelung Georgensgmünd',
    description: 'Entrümpelung in Georgensgmünd.',
    distance: '30 km',
    population: '6.000',
    postalCodes: ['91166'],
    lat: 49.1817,
    lng: 11.0061,
    priority: 'low',
  },

  // Fürth - Umland
  {
    name: 'Zirndorf',
    slug: 'zirndorf',
    title: 'Entrümpelung Zirndorf',
    description: 'Entrümpelung in Zirndorf.',
    distance: '22 km',
    population: '26.000',
    postalCodes: ['90513'],
    lat: 49.4453,
    lng: 10.9531,
    priority: 'high',
  },
  {
    name: 'Oberasbach',
    slug: 'oberasbach',
    title: 'Entrümpelung Oberasbach',
    description: 'Entrümpelung in Oberasbach.',
    distance: '18 km',
    population: '18.000',
    postalCodes: ['90522'],
    lat: 49.4289,
    lng: 10.9639,
    priority: 'high',
  },
  {
    name: 'Stein',
    slug: 'stein',
    title: 'Entrümpelung Stein',
    description: 'Entrümpelung in Stein bei Nürnberg.',
    distance: '16 km',
    population: '14.000',
    postalCodes: ['90547'],
    lat: 49.4133,
    lng: 11.0167,
    priority: 'high',
  },
  {
    name: 'Langenzenn',
    slug: 'langenzenn',
    title: 'Entrümpelung Langenzenn',
    description: 'Entrümpelung in Langenzenn.',
    distance: '30 km',
    population: '10.500',
    postalCodes: ['90579'],
    lat: 49.4972,
    lng: 10.7944,
    priority: 'high',
  },
  {
    name: 'Roßtal',
    slug: 'rosstal',
    title: 'Entrümpelung Roßtal',
    description: 'Entrümpelung in Roßtal.',
    distance: '28 km',
    population: '10.000',
    postalCodes: ['90574'],
    lat: 49.3950,
    lng: 10.8806,
    priority: 'low',
  },
  {
    name: 'Cadolzburg',
    slug: 'cadolzburg',
    title: 'Entrümpelung Cadolzburg',
    description: 'Entrümpelung in Cadolzburg.',
    distance: '32 km',
    population: '11.000',
    postalCodes: ['90556'],
    lat: 49.4547,
    lng: 10.8572,
    priority: 'low',
  },
  {
    name: 'Wilhermsdorf',
    slug: 'wilhermsdorf',
    title: 'Entrümpelung Wilhermsdorf',
    description: 'Entrümpelung in Wilhermsdorf.',
    distance: '42 km',
    population: '5.200',
    postalCodes: ['91452'],
    lat: 49.4803,
    lng: 10.7144,
    priority: 'low',
  },

  // Neumarkt & Umgebung
  {
    name: 'Berching',
    slug: 'berching',
    title: 'Entrümpelung Berching',
    description: 'Entrümpelung in Berching.',
    distance: '52 km',
    population: '8.700',
    postalCodes: ['92334'],
    lat: 49.1061,
    lng: 11.4453,
    priority: 'low',
  },
  {
    name: 'Dietfurt',
    slug: 'dietfurt',
    title: 'Entrümpelung Dietfurt',
    description: 'Entrümpelung in Dietfurt.',
    distance: '58 km',
    population: '6.000',
    postalCodes: ['92345'],
    lat: 49.0344,
    lng: 11.5867,
    priority: 'low',
  },
  {
    name: 'Freystadt',
    slug: 'freystadt',
    title: 'Entrümpelung Freystadt',
    description: 'Entrümpelung in Freystadt.',
    distance: '45 km',
    population: '9.400',
    postalCodes: ['92342'],
    lat: 49.2003,
    lng: 11.3400,
    priority: 'low',
  },
  {
    name: 'Parsberg',
    slug: 'parsberg',
    title: 'Entrümpelung Parsberg',
    description: 'Entrümpelung in Parsberg.',
    distance: '62 km',
    population: '6.900',
    postalCodes: ['92331'],
    lat: 49.1597,
    lng: 11.7147,
    priority: 'low',
  },
  {
    name: 'Postbauer-Heng',
    slug: 'postbauer-heng',
    title: 'Entrümpelung Postbauer-Heng',
    description: 'Entrümpelung in Postbauer-Heng.',
    distance: '32 km',
    population: '6.200',
    postalCodes: ['92353'],
    lat: 49.3686,
    lng: 11.4019,
    priority: 'low',
  },
  {
    name: 'Seubersdorf',
    slug: 'seubersdorf',
    title: 'Entrümpelung Seubersdorf',
    description: 'Entrümpelung in Seubersdorf.',
    distance: '48 km',
    population: '4.700',
    postalCodes: ['92358'],
    lat: 49.2589,
    lng: 11.6561,
    priority: 'low',
  },

  // Weitere Orte im 70km Radius
  {
    name: 'Treuchtlingen',
    slug: 'treuchtlingen',
    title: 'Entrümpelung Treuchtlingen',
    description: 'Entrümpelung in Treuchtlingen.',
    distance: '68 km',
    population: '13.000',
    postalCodes: ['91757'],
    lat: 48.9558,
    lng: 10.9078,
    priority: 'low',
  },
  {
    name: 'Ellingen',
    slug: 'ellingen',
    title: 'Entrümpelung Ellingen',
    description: 'Entrümpelung in Ellingen.',
    distance: '58 km',
    population: '3.800',
    postalCodes: ['91792'],
    lat: 49.0650,
    lng: 10.9692,
    priority: 'low',
  },
  {
    name: 'Pappenheim',
    slug: 'pappenheim',
    title: 'Entrümpelung Pappenheim',
    description: 'Entrümpelung in Pappenheim.',
    distance: '65 km',
    population: '4.100',
    postalCodes: ['91788'],
    lat: 48.9319,
    lng: 10.9739,
    priority: 'low',
  },
  {
    name: 'Pleinfeld',
    slug: 'pleinfeld',
    title: 'Entrümpelung Pleinfeld',
    description: 'Entrümpelung in Pleinfeld.',
    distance: '52 km',
    population: '7.800',
    postalCodes: ['91785'],
    lat: 49.1028,
    lng: 10.9750,
    priority: 'low',
  },
  {
    name: 'Herrieden',
    slug: 'herrieden',
    title: 'Entrümpelung Herrieden',
    description: 'Entrümpelung in Herrieden.',
    distance: '68 km',
    population: '7.800',
    postalCodes: ['91567'],
    lat: 49.2264,
    lng: 10.4950,
    priority: 'low',
  },
  {
    name: 'Feuchtwangen',
    slug: 'feuchtwangen',
    title: 'Entrümpelung Feuchtwangen',
    description: 'Entrümpelung in Feuchtwangen.',
    distance: '70 km',
    population: '12.500',
    postalCodes: ['91555'],
    lat: 49.1689,
    lng: 10.3289,
    priority: 'low',
  },
  {
    name: 'Ornbau',
    slug: 'ornbau',
    title: 'Entrümpelung Ornbau',
    description: 'Entrümpelung in Ornbau.',
    distance: '62 km',
    population: '1.600',
    postalCodes: ['91737'],
    lat: 49.1619,
    lng: 10.7094,
    priority: 'low',
  },
  {
    name: 'Merkendorf',
    slug: 'merkendorf',
    title: 'Entrümpelung Merkendorf',
    description: 'Entrümpelung in Merkendorf.',
    distance: '68 km',
    population: '3.000',
    postalCodes: ['91732'],
    lat: 49.1967,
    lng: 10.6722,
    priority: 'low',
  },

  // ========== WEITERE KLEINE GEMEINDEN & DÖRFER (Maximal SEO) ==========
  
  // Nürnberger Land - Zusätzliche Orte
  {
    name: 'Offenhausen',
    slug: 'offenhausen',
    title: 'Entrümpelung Offenhausen',
    description: 'Entrümpelung in Offenhausen.',
    distance: '22 km',
    population: '1.200',
    postalCodes: ['91238'],
    lat: 49.5142,
    lng: 11.3803,
    priority: 'low',
  },
  {
    name: 'Henfenfeld',
    slug: 'henfenfeld',
    title: 'Entrümpelung Henfenfeld',
    description: 'Entrümpelung in Henfenfeld.',
    distance: '18 km',
    population: '2.100',
    postalCodes: ['91239'],
    lat: 49.4856,
    lng: 11.3606,
    priority: 'low',
  },
  {
    name: 'Kirchensittenbach',
    slug: 'kirchensittenbach',
    title: 'Entrümpelung Kirchensittenbach',
    description: 'Entrümpelung in Kirchensittenbach.',
    distance: '20 km',
    population: '1.800',
    postalCodes: ['91241'],
    lat: 49.5361,
    lng: 11.3461,
    priority: 'low',
  },
  {
    name: 'Vorra',
    slug: 'vorra',
    title: 'Entrümpelung Vorra',
    description: 'Entrümpelung in Vorra.',
    distance: '25 km',
    population: '1.600',
    postalCodes: ['91247'],
    lat: 49.5483,
    lng: 11.3578,
    priority: 'low',
  },
  {
    name: 'Hartenstein',
    slug: 'hartenstein',
    title: 'Entrümpelung Hartenstein',
    description: 'Entrümpelung in Hartenstein.',
    distance: '30 km',
    population: '900',
    postalCodes: ['91235'],
    lat: 49.5644,
    lng: 11.5186,
    priority: 'low',
  },
  {
    name: 'Pegnitz',
    slug: 'pegnitz',
    title: 'Entrümpelung Pegnitz',
    description: 'Entrümpelung in Pegnitz.',
    distance: '48 km',
    population: '14.000',
    postalCodes: ['91257'],
    lat: 49.7575,
    lng: 11.5458,
    priority: 'low',
  },
  {
    name: 'Auerbach',
    slug: 'auerbach',
    title: 'Entrümpelung Auerbach',
    description: 'Entrümpelung in Auerbach in der Oberpfalz.',
    distance: '60 km',
    population: '9.500',
    postalCodes: ['91275'],
    lat: 49.6892,
    lng: 11.6353,
    priority: 'low',
  },
  {
    name: 'Königstein',
    slug: 'koenigstein',
    title: 'Entrümpelung Königstein',
    description: 'Entrümpelung in Königstein.',
    distance: '32 km',
    population: '1.600',
    postalCodes: ['91224'],
    lat: 49.6133,
    lng: 11.6167,
    priority: 'low',
  },
  {
    name: 'Simmelsdorf',
    slug: 'simmelsdorf',
    title: 'Entrümpelung Simmelsdorf',
    description: 'Entrümpelung in Simmelsdorf.',
    distance: '24 km',
    population: '2.600',
    postalCodes: ['91245'],
    lat: 49.5386,
    lng: 11.4158,
    priority: 'low',
  },
  {
    name: 'Hohenstadt',
    slug: 'hohenstadt',
    title: 'Entrümpelung Hohenstadt',
    description: 'Entrümpelung in Hohenstadt.',
    distance: '26 km',
    population: '1.500',
    postalCodes: ['91235'],
    lat: 49.5561,
    lng: 11.5028,
    priority: 'low',
  },

  // Erlangen-Höchstadt - Zusätzliche Gemeinden
  {
    name: 'Adelsdorf',
    slug: 'adelsdorf',
    title: 'Entrümpelung Adelsdorf',
    description: 'Entrümpelung in Adelsdorf.',
    distance: '38 km',
    population: '8.700',
    postalCodes: ['91325'],
    lat: 49.7067,
    lng: 10.8989,
    priority: 'low',
  },
  {
    name: 'Aurachtal',
    slug: 'aurachtal',
    title: 'Entrümpelung Aurachtal',
    description: 'Entrümpelung in Aurachtal.',
    distance: '42 km',
    population: '3.900',
    postalCodes: ['91086'],
    lat: 49.6856,
    lng: 10.9164,
    priority: 'low',
  },
  {
    name: 'Gremsdorf',
    slug: 'gremsdorf',
    title: 'Entrümpelung Gremsdorf',
    description: 'Entrümpelung in Gremsdorf.',
    distance: '46 km',
    population: '4.200',
    postalCodes: ['91350'],
    lat: 49.7272,
    lng: 10.8403,
    priority: 'low',
  },
  {
    name: 'Lonnerstadt',
    slug: 'lonnerstadt',
    title: 'Entrümpelung Lonnerstadt',
    description: 'Entrümpelung in Lonnerstadt.',
    distance: '48 km',
    population: '3.700',
    postalCodes: ['91475'],
    lat: 49.7058,
    lng: 10.7606,
    priority: 'low',
  },
  {
    name: 'Mühlhausen',
    slug: 'muehlhausen',
    title: 'Entrümpelung Mühlhausen',
    description: 'Entrümpelung in Mühlhausen.',
    distance: '34 km',
    population: '3.800',
    postalCodes: ['91091'],
    lat: 49.6683,
    lng: 11.0228,
    priority: 'low',
  },
  {
    name: 'Vestenbergsgreuth',
    slug: 'vestenbergsgreuth',
    title: 'Entrümpelung Vestenbergsgreuth',
    description: 'Entrümpelung in Vestenbergsgreuth.',
    distance: '52 km',
    population: '1.900',
    postalCodes: ['91472'],
    lat: 49.7361,
    lng: 10.7344,
    priority: 'low',
  },
  {
    name: 'Wachenroth',
    slug: 'wachenroth',
    title: 'Entrümpelung Wachenroth',
    description: 'Entrümpelung in Wachenroth.',
    distance: '50 km',
    population: '2.400',
    postalCodes: ['96193'],
    lat: 49.7744,
    lng: 10.7542,
    priority: 'low',
  },
  {
    name: 'Röttenbach (Erh)',
    slug: 'roettenbach-erh',
    title: 'Entrümpelung Röttenbach',
    description: 'Entrümpelung in Röttenbach bei Erlangen.',
    distance: '32 km',
    population: '2.600',
    postalCodes: ['91341'],
    lat: 49.6689,
    lng: 10.9747,
    priority: 'low',
  },

  // Fürth-Land - Zusätzliche Gemeinden
  {
    name: 'Ammerndorf',
    slug: 'ammerndorf',
    title: 'Entrümpelung Ammerndorf',
    description: 'Entrümpelung in Ammerndorf.',
    distance: '24 km',
    population: '2.100',
    postalCodes: ['90614'],
    lat: 49.4883,
    lng: 10.8967,
    priority: 'low',
  },
  {
    name: 'Seukendorf',
    slug: 'seukendorf',
    title: 'Entrümpelung Seukendorf',
    description: 'Entrümpelung in Seukendorf.',
    distance: '26 km',
    population: '3.700',
    postalCodes: ['90556'],
    lat: 49.4764,
    lng: 10.8694,
    priority: 'low',
  },
  {
    name: 'Veitsbronn',
    slug: 'veitsbronn',
    title: 'Entrümpelung Veitsbronn',
    description: 'Entrümpelung in Veitsbronn.',
    distance: '22 km',
    population: '6.800',
    postalCodes: ['90587'],
    lat: 49.4764,
    lng: 10.9247,
    priority: 'low',
  },
  {
    name: 'Großhabersdorf',
    slug: 'grosshabersdorf',
    title: 'Entrümpelung Großhabersdorf',
    description: 'Entrümpelung in Großhabersdorf.',
    distance: '34 km',
    population: '4.300',
    postalCodes: ['90613'],
    lat: 49.4819,
    lng: 10.7858,
    priority: 'low',
  },
  {
    name: 'Obermichelbach',
    slug: 'obermichelbach',
    title: 'Entrümpelung Obermichelbach',
    description: 'Entrümpelung in Obermichelbach.',
    distance: '28 km',
    population: '3.200',
    postalCodes: ['90617'],
    lat: 49.4417,
    lng: 10.8558,
    priority: 'low',
  },
  {
    name: 'Tuchenbach',
    slug: 'tuchenbach',
    title: 'Entrümpelung Tuchenbach',
    description: 'Entrümpelung in Tuchenbach.',
    distance: '26 km',
    population: '1.800',
    postalCodes: ['90587'],
    lat: 49.4561,
    lng: 10.9039,
    priority: 'low',
  },

  // Landkreis Roth - Zusätzliche Gemeinden
  {
    name: 'Büchenbach',
    slug: 'buechenbach',
    title: 'Entrümpelung Büchenbach',
    description: 'Entrümpelung in Büchenbach.',
    distance: '22 km',
    population: '5.200',
    postalCodes: ['91186'],
    lat: 49.2961,
    lng: 11.1189,
    priority: 'low',
  },
  {
    name: 'Kammerstein',
    slug: 'kammerstein',
    title: 'Entrümpelung Kammerstein',
    description: 'Entrümpelung in Kammerstein.',
    distance: '28 km',
    population: '2.700',
    postalCodes: ['91126'],
    lat: 49.3056,
    lng: 11.0000,
    priority: 'low',
  },
  {
    name: 'Schwanstetten',
    slug: 'schwanstetten',
    title: 'Entrümpelung Schwanstetten',
    description: 'Entrümpelung in Schwanstetten.',
    distance: '16 km',
    population: '9.800',
    postalCodes: ['90596'],
    lat: 49.3333,
    lng: 11.0833,
    priority: 'low',
  },
  {
    name: 'Rohr',
    slug: 'rohr',
    title: 'Entrümpelung Rohr',
    description: 'Entrümpelung in Rohr bei Nürnberg.',
    distance: '18 km',
    population: '7.100',
    postalCodes: ['91189'],
    lat: 49.2917,
    lng: 11.1500,
    priority: 'low',
  },
  {
    name: 'Pyrbaum',
    slug: 'pyrbaum',
    title: 'Entrümpelung Pyrbaum',
    description: 'Entrümpelung in Pyrbaum.',
    distance: '32 km',
    population: '3.300',
    postalCodes: ['90602'],
    lat: 49.2278,
    lng: 11.3667,
    priority: 'low',
  },
  {
    name: 'Heideck',
    slug: 'heideck',
    title: 'Entrümpelung Heideck',
    description: 'Entrümpelung in Heideck.',
    distance: '38 km',
    population: '5.300',
    postalCodes: ['91180'],
    lat: 49.1667,
    lng: 11.1500,
    priority: 'low',
  },
  {
    name: 'Belmbrach',
    slug: 'belmbrach',
    title: 'Entrümpelung Belmbrach',
    description: 'Entrümpelung in Belmbrach.',
    distance: '42 km',
    population: '1.100',
    postalCodes: ['91171'],
    lat: 49.0594,
    lng: 11.2819,
    priority: 'low',
  },

  // Neumarkt - Zusätzliche Gemeinden
  {
    name: 'Berg bei Neumarkt',
    slug: 'berg-neumarkt',
    title: 'Entrümpelung Berg',
    description: 'Entrümpelung in Berg bei Neumarkt.',
    distance: '35 km',
    population: '5.800',
    postalCodes: ['92348'],
    lat: 49.3658,
    lng: 11.5369,
    priority: 'low',
  },
  {
    name: 'Lauterhofen',
    slug: 'lauterhofen',
    title: 'Entrümpelung Lauterhofen',
    description: 'Entrümpelung in Lauterhofen.',
    distance: '52 km',
    population: '2.600',
    postalCodes: ['92283'],
    lat: 49.3542,
    lng: 11.6386,
    priority: 'low',
  },
  {
    name: 'Lupburg',
    slug: 'lupburg',
    title: 'Entrümpelung Lupburg',
    description: 'Entrümpelung in Lupburg.',
    distance: '58 km',
    population: '2.700',
    postalCodes: ['92331'],
    lat: 49.2236,
    lng: 11.7750,
    priority: 'low',
  },
  {
    name: 'Velburg',
    slug: 'velburg',
    title: 'Entrümpelung Velburg',
    description: 'Entrümpelung in Velburg.',
    distance: '55 km',
    population: '5.200',
    postalCodes: ['92355'],
    lat: 49.2292,
    lng: 11.6608,
    priority: 'low',
  },
  {
    name: 'Mühlhausen (Oberpfalz)',
    slug: 'muehlhausen-oberpfalz',
    title: 'Entrümpelung Mühlhausen',
    description: 'Entrümpelung in Mühlhausen in der Oberpfalz.',
    distance: '48 km',
    population: '2.400',
    postalCodes: ['92360'],
    lat: 49.2697,
    lng: 11.5608,
    priority: 'low',
  },
  {
    name: 'Pilsach',
    slug: 'pilsach',
    title: 'Entrümpelung Pilsach',
    description: 'Entrümpelung in Pilsach.',
    distance: '62 km',
    population: '2.000',
    postalCodes: ['92367'],
    lat: 49.2975,
    lng: 11.7631,
    priority: 'low',
  },
  {
    name: 'Deining',
    slug: 'deining',
    title: 'Entrümpelung Deining',
    description: 'Entrümpelung in Deining.',
    distance: '50 km',
    population: '4.200',
    postalCodes: ['92364'],
    lat: 49.1614,
    lng: 11.5386,
    priority: 'low',
  },

  // Weißenburg-Gunzenhausen - Zusätzliche Gemeinden
  {
    name: 'Nennslingen',
    slug: 'nennslingen',
    title: 'Entrümpelung Nennslingen',
    description: 'Entrümpelung in Nennslingen.',
    distance: '52 km',
    population: '1.900',
    postalCodes: ['91790'],
    lat: 48.9858,
    lng: 10.9264,
    priority: 'low',
  },
  {
    name: 'Markt Berolzheim',
    slug: 'markt-berolzheim',
    title: 'Entrümpelung Markt Berolzheim',
    description: 'Entrümpelung in Markt Berolzheim.',
    distance: '62 km',
    population: '1.600',
    postalCodes: ['91801'],
    lat: 49.0117,
    lng: 10.8644,
    priority: 'low',
  },
  {
    name: 'Dittenheim',
    slug: 'dittenheim',
    title: 'Entrümpelung Dittenheim',
    description: 'Entrümpelung in Dittenheim.',
    distance: '58 km',
    population: '1.700',
    postalCodes: ['91723'],
    lat: 49.0636,
    lng: 10.7781,
    priority: 'low',
  },
  {
    name: 'Muhr am See',
    slug: 'muhr-am-see',
    title: 'Entrümpelung Muhr am See',
    description: 'Entrümpelung in Muhr am See.',
    distance: '62 km',
    population: '2.000',
    postalCodes: ['91735'],
    lat: 49.1347,
    lng: 10.7258,
    priority: 'low',
  },
  {
    name: 'Absberg',
    slug: 'absberg',
    title: 'Entrümpelung Absberg',
    description: 'Entrümpelung in Absberg.',
    distance: '58 km',
    population: '1.500',
    postalCodes: ['91720'],
    lat: 49.1228,
    lng: 10.8547,
    priority: 'low',
  },
  {
    name: 'Theilenhofen',
    slug: 'theilenhofen',
    title: 'Entrümpelung Theilenhofen',
    description: 'Entrümpelung in Theilenhofen.',
    distance: '48 km',
    population: '1.800',
    postalCodes: ['91741'],
    lat: 49.0908,
    lng: 10.8192,
    priority: 'low',
  },

  // Ansbach-Land - Zusätzliche Gemeinden
  {
    name: 'Lichtenau',
    slug: 'lichtenau',
    title: 'Entrümpelung Lichtenau',
    description: 'Entrümpelung in Lichtenau bei Ansbach.',
    distance: '65 km',
    population: '5.100',
    postalCodes: ['91586'],
    lat: 49.2758,
    lng: 10.6900,
    priority: 'low',
  },
  {
    name: 'Lehrberg',
    slug: 'lehrberg',
    title: 'Entrümpelung Lehrberg',
    description: 'Entrümpelung in Lehrberg.',
    distance: '68 km',
    population: '3.200',
    postalCodes: ['91611'],
    lat: 49.3194,
    lng: 10.4792,
    priority: 'low',
  },
  {
    name: 'Heilsbronn',
    slug: 'heilsbronn',
    title: 'Entrümpelung Heilsbronn',
    description: 'Entrümpelung in Heilsbronn.',
    distance: '42 km',
    population: '9.400',
    postalCodes: ['91560'],
    lat: 49.3383,
    lng: 10.7933,
    priority: 'low',
  },
  {
    name: 'Windsbach',
    slug: 'windsbach',
    title: 'Entrümpelung Windsbach',
    description: 'Entrümpelung in Windsbach.',
    distance: '48 km',
    population: '6.200',
    postalCodes: ['91575'],
    lat: 49.2450,
    lng: 10.8244,
    priority: 'low',
  },
  {
    name: 'Neuendettelsau',
    slug: 'neuendettelsau',
    title: 'Entrümpelung Neuendettelsau',
    description: 'Entrümpelung in Neuendettelsau.',
    distance: '52 km',
    population: '7.800',
    postalCodes: ['91564'],
    lat: 49.2892,
    lng: 10.7833,
    priority: 'low',
  },
  {
    name: 'Dietenhofen',
    slug: 'dietenhofen',
    title: 'Entrümpelung Dietenhofen',
    description: 'Entrümpelung in Dietenhofen.',
    distance: '38 km',
    population: '6.600',
    postalCodes: ['90599'],
    lat: 49.3925,
    lng: 10.7519,
    priority: 'low',
  },
  {
    name: 'Petersaurach',
    slug: 'petersaurach',
    title: 'Entrümpelung Petersaurach',
    description: 'Entrümpelung in Petersaurach.',
    distance: '55 km',
    population: '3.000',
    postalCodes: ['91580'],
    lat: 49.3536,
    lng: 10.6031,
    priority: 'low',
  },
]

// Service types for programmatic SEO
export interface ServiceType {
  slug: string
  title: string
  description: string
  benefits: string[]
}

export const serviceTypes: ServiceType[] = [
  {
    slug: 'entruempelung',
    title: 'Entrümpelung',
    description: 'Professionelle Entrümpelung von Häusern, Wohnungen, Kellern und Dachböden',
    benefits: [
      'Schnelle Abwicklung',
      'Faire Preisgestaltung',
      'Komplette Entsorgung',
      'Besenreine Übergabe',
    ],
  },
  {
    slug: 'haushaltsaufloesung',
    title: 'Haushaltsauflösung',
    description: 'Komplette Auflösung von Haushalten mit Wertanrechnung für verwertbare Gegenstände',
    benefits: [
      'Wertanrechnung möglich',
      'Professionelle Abwicklung',
      'Diskrete Durchführung',
      'Entsorgung & Verkauf',
    ],
  },
  {
    slug: 'wohnungsaufloesung',
    title: 'Wohnungsauflösung',
    description: 'Professionelle Wohnungsauflösung – schnell, diskret und zuverlässig',
    benefits: [
      'Schnelle Terminvergabe',
      'Komplettservice',
      'Faire Preise',
      'Fachgerechte Entsorgung',
    ],
  },
]
